version: '3.1'

services:
  db:
    image: postgres
#    restart: no
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: monitor
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
      - ./docker/db/dumps:/dumps
